apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: frontend-deployment 
  namespace: retail 
spec:
  replicas: 1
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1
  selector: 
    matchLabels:
      app : retail 
  template:
    metadata:
      labels:
        app: retail 
    spec:
      containers:
        - name: retail-cont 
          image: muralisocial123/retail-app:v-26
          port:
            - containerPort: 
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: retail-secret 
                  key: PORT
            - name: EMAIL_SERVICE
              valueFrom:
                secretKeyRef: 
                  name: retail-secret 
                  key: EMAIL_SERVICE
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: retail-secret 
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: retail-secret 
                  key: EMAIL_PASS
            - name: SUPPORT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: retail-secret 
                  key: SUPPORT_EMAIL
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: retail-secret 
                  key: ADMIN_USERNAME
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: retail-secret 
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retail-secret 
                  key: ADMIN_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapRef:
                  name: retail-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapRef:
                  name: retail-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapRef:
                  name: retail-config
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapRef:
                  name: retail-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapRef:
                  name: retail-config
                  key: DB_PORT
            
                              
                


      