apiVersion: v1 
kind: Secret 
metadata:
  name: retail-secret 
  namespace: retail 
type: Opaque 
stringData:
  PORT: "3000"
  
  
  EMAIL_SERVICE: "gmail"
  EMAIL_USER: "vasuvarshney2002@gmail.com"
  EMAIL_PASS: "spsq ulhf ockl eumq"
  SUPPORT_EMAIL: "your-support@email.com"
  ADMIN_USERNAME: "admin"
  ADMIN_EMAIL: "admin@your-domain.com"
  ADMIN_PASSWORD: "secure-admin-password"